Nosto/nosto-prestashop

- nostotagging.php
> Require existing account before outputting any rec divs or tagging

- nostotagging.php
- views/templates/hook/header_meta-tags.tpl
> Add meta tags to <head> section of every page that hold info about the installed module

- nostotagging.php
> Add employee first name, last name and email to iframe params

- classes/helpers/config.php
- nostotagging.php
- views/templates/admin/config-bootstrap.tpl
> Add setting for where to render default tagging

- nostotagging.php
- views/templates/hook/404_hidden_nosto-elements.tpl
- views/templates/hook/order-confirmation_hidden_nosto-elements.tpl
> Add tagging for 404 pages and order confirmation page

- CHANGELOG.md
- classes/helpers/config.php
- controllers/front/oauth2.php
- nostotagging.php
- upgrade/upgrade-2.6.R4.php
> Clear cache after Nosto account installation and uninstallation

- CHANGELOG.md
- classes/helpers/currency.php
- config.xml
- nostotagging.php
* Fixed the not-found controller for Prestashop 1.4
* Fixed the exclusion of deleted currencies in Prestashop 1.7
Closes #95
> Consolidate all tagging including order and product tagging

- controllers/front/order.php
- controllers/front/product.php
> Support for specifying the identifier of the order and product when exporting

- nostotagging.php
- views/js/nostotagging-auto-slots.js
- views/templates/hook/header_embed-script.tpl
> Added a fix to prevent loading the Nosto recommendations twice

- nostotagging.php
> Add more visible errors if the installation fails

- nostotagging.php
- views/templates/hook/top_page_type-tagging.tpl
> Add page type tagging

- classes/models/product.php
- composer.json
- composer.lock
- views/templates/hook/footer-product_product-tagging.tpl
> Remove date published from product tagging and product model

- views/templates/hook/header_embed-script.tpl
> Use direct include for Nosto script

- classes/helpers/config.php
- classes/helpers/image.php
- classes/helpers/url.php
- classes/models/product.php
- nostotagging.php
- views/templates/admin/config-bootstrap.tpl
- views/templates/admin/legacy-config-bootstrap.tpl
> Implement possibility to choose which image to use for recommendations

- views/templates/hook/header_add-to-cart.tpl
> Fix add to cart to send product viewed event

- classes/helpers/url.php
- classes/meta/account-iframe.php
- composer.json
- composer.lock
Add recent sales and visits information to the iframe url
> Add recent sales and visits information to the iframe url

- CHANGELOG.md
- classes/meta/account-iframe.php
- nostotagging.php
Fix the bug that it doesn’t work with some prestashop version
> Fix the bug that it doesn’t work with some prestashop version

- classes/services/NostoSignupService.php
- controllers/admin/NostoAdvancedSettingController.php
> Catch and log api call exceptions

- classes/blocks/NostoDefaultTagging.php
- nostotagging.php
> Render nostotagging on footer or top based on setting

- classes/Nosto.php
- classes/blocks/NostoVariationTagging.php
- classes/managers/NostoAdminTabManager.php
- classes/managers/notifications/NostoCheckMulticurrencyNotification.php
- classes/models/NostoProduct.php
- classes/models/NostoSku.php
- classes/models/meta/NostoAccountSignup.php
- classes/services/NostoOrderService.php
- composer.json
- composer.lock
- nostotagging.php
> Test and fix

- controllers/admin/NostoBaseController.php
- controllers/admin/NostoIndexController.php
- nostotagging.php
- Fix language selection related issues
- Show notification if nosto module is disabled for current sub shop
- Do not show nosto page if current scope is global
> Fix language selection related issues

- classes/helpers/NostoHelperPrice.php
If multi-store is enable and stores have different default currencies, the product update api got incorrect price
> Fix multi currency issue

- CHANGELOG.md
- nostotagging.php
Fix the issue that nosto plugin injects notification content to prestashop ajax responses
> Release 2.8.8

- CHANGELOG.md
- nostotagging.php
> Release 2.8.9

- classes/managers/notifications/NostoCheckMulticurrencyNotification.php
- classes/models/NostoCart.php
- classes/models/NostoProduct.php
- classes/models/NostoSku.php
- composer.json
- composer.lock
- nostotagging.php
Fixed: 
- Variations not showing in the debug toolbar issue; 
- Notification missing issue;
-  Import api failing issue; 
- Cart tagging price rounding issue.
> Fix cart tagging price rounding and a few other issues

- CHANGELOG.md
- classes/models/NostoProduct.php
- nostotagging.php
Fixed the issue that some products got incorrect images if there was a combination with id 0
> Hotfix 3.0.2

- CHANGELOG.md
- composer.json
- composer.lock
- nostotagging.php
Update sdk to update tag1, tag2 and tag3 to tagsX
> Hotfix 3.0.3

- classes/models/NostoProduct.php
> Add custom fields to product

- classes/models/NostoCart.php
- classes/models/NostoOrder.php
- composer.json
- composer.lock
> Add sku id to cart and order tagging

- CHANGELOG.md
- composer.json
- composer.lock
- nostotagging.php
Update SDK version to fix the custom field keys snake case conversion issue
Closes #210
> Hotfix 3.2.3

- CHANGELOG.md
- Dockerfile
- classes/services/NostoCartService.php
- nostotagging.php
Fix the bug that could not add product to cart without nosto account
> hotfix 3.2.4

- classes/services/NostoProductService.php
https://nostosolutions.atlassian.net/browse/NS-2137
> Add a work around if there is no employee in the context

- CHANGELOG.md
- nostotagging.php
Fixed a bug that nosto injects html content to prestashop ajax responses on older prestashop version.
Ticket: https://nostosolutions.atlassian.net/browse/NS-2184
> hotfix 3.3.1

- CHANGELOG.md
- nostotagging.php
- views/templates/hook/partials/js-auto-slots-inline.tpl
Fix that the auto slot javascript is not working properly if javascript function run before the page html fully loaded to the browser.
> hotfix 3.3.3

- classes/helpers/NostoHelperConfig.php
- classes/models/NostoCustomer.php
- classes/models/NostoOrder.php
- classes/models/order/NostoOrderBuyer.php
- controllers/admin/NostoAdvancedSettingController.php
- controllers/admin/NostoIndexController.php
- views/templates/admin/config-bootstrap.tpl
> Customer info switch

- classes/blocks/NostoCustomerTagging.php
- classes/blocks/NostoPageTypeTagging.php
- classes/models/NostoCategory.php
- classes/models/NostoSearch.php
- composer.json
- composer.lock
Bump SDK to support Category overriding
Closes #232 
Closes #233
> Bump SDK and use new SDK Category and PageType models

- classes/models/NostoCart.php
Render cart tagging without item in cart so that it could empty the cart in nosto end
Closes #234
> Render cart tagging without item in cart

- CHANGELOG.md
- nostotagging.php
Fixed a issue that it failed to be installed to some special prestashop environments. Related ticket https://nostosolutions.atlassian.net/browse/NS-2367
> hotfix 3.4.1

- classes/models/NostoProduct.php
> Fix Negative SKU Inventory Handling In Product Availability

- CHANGELOG.md
- classes/helpers/NostoHelperController.php
- classes/managers/NostoAdminTabManager.php
- nostotagging.php
Fixed a bug that it failed to be installed to prestashop below version 1.6.1.0 with multi-language enabled
Closes: #259
> Hotfix 3.5.2

- composer.json
- composer.lock
Bumpo SDK to `3.9.2` to handle serializing the product HTML when price is zero
closes #279
> Bump PHP SDK to 3.9.2 

- Dockerfile
- classes/helpers/NostoHelperContext.php
- controllers/front/OauthTraitAdapter.php
Added check that allow to reconnect the same account to the same shop in the same language. 
closes #294
Manually
> Allow reconnecting the same account to the same scope

- classes/helpers/NostoHelperUrl.php
- classes/services/NostoOrderService.php
- classes/services/NostoProductService.php
Send active domain with API calls when upserting product and creating order.
closes #280
> Send store url with API calls

- CHANGELOG.md
- Dockerfile
- Jenkinsfile
- composer.json
- composer.lock
- nostotagging.php
Update outdated composer dependencies.
Fixes #304 
N/A
> Hotfix - Update Dependencies

- .github/workflows/action.yml
- .github/workflows/phan.yml
- CHANGELOG.md
- classes/helpers/NostoHelperPrice.php
- classes/helpers/NostoHelperVariation.php
- composer.json
- composer.lock
- phan.php
- views/templates/admin/config-bootstrap.tpl
- views/templates/admin/legacy-config-bootstrap.tpl
Reverts Nosto/nosto-prestashop#316
> Revert "Show correct price based on include_tax"

- .github/workflows/action.yml
- .github/workflows/phan.yml
- CHANGELOG.md
- classes/helpers/NostoHelperPrice.php
- classes/helpers/NostoHelperVariation.php
- composer.json
- composer.lock
- nostotagging.php
- phan.php
- views/templates/admin/config-bootstrap.tpl
- views/templates/admin/legacy-config-bootstrap.tpl
Reverts Nosto/nosto-prestashop#317
> Revert "Revert "Show correct price based on include_tax""

- CHANGELOG.md
- composer.json
- composer.lock
- nostotagging.php
Round prices to 2 decimal accuracy
> Hotfix 3.9.3 - Round prices to 2 decimal accuracy 

- Dockerfile
- bootstrap.php
- classes/helpers/NostoHelperUrl.php
- classes/models/NostoConnection.php
- composer.lock
- controllers/admin/NostoCreateAccountController.php
- controllers/admin/NostoDeleteAccountController.php
- controllers/admin/NostoIndexController.php
- controllers/admin/NostoOpenAccountController.php
- controllers/front/OauthTraitAdapter.php
- nostotagging.php
- views/templates/admin/config-bootstrap.tpl
Modify module to work on Prestashop versions 1.6.x.x
> Feature/support prestashop 1.6.x.x

- CHANGELOG.md
- controllers/admin/NostoOpenAccountController.php
- nostotagging.php
Minor improvement. Always redirect to Nosto dashboard
> Always redirect to Nosto dashboard

- CHANGELOG.md
- classes/services/NostoOrderService.php
- nostotagging.php
Fix the bug where order is sent to all shops with multistore setup
> Fix the bug where order is sent to all shops with multistore setup

- CHANGELOG.md
- classes/helpers/NostoHelperPrice.php
- classes/models/NostoProduct.php
- nostotagging.php
Remove tax calculation from supplier cost in product builder
> Remove tax calculation from supplier cost in product builder

- classes/helpers/NostoHelperPrice.php
Replace if with ternary clause
> Replace if with ternary clause

- build.xml
> Remove version replacement during phing packaging

- classes/models/NostoProduct.php
- composer.json
- composer.lock
> Set category ids for the product in the builder

- CHANGELOG.md
- build.xml
- classes/helpers/NostoHelperController.php
- classes/helpers/NostoHelperFlash.php
- classes/models/NostoProduct.php
- classes/models/NostoSku.php
- composer.json
- composer.lock
- nostotagging.php
> Release 4.1.0

- .github/workflows/ide.yml
- CHANGELOG.md
- composer.json
- composer.lock
- nostotagging.php
Update php-sdk to fix the issue that the category_ids of nosto product is rendered incorrectly
This has been tested by checking in browser after updated
> 4.1.1 Update php-sdk to fix category_ids render incorrectly

- classes/models/NostoProduct.php
- composer.json
- composer.lock
> add parent category id's to tagging and API

- CHANGELOG.md
- nostotagging.php
> Release 4.4.0 - Compatibility prestashop 8.1

- .github/workflows/action.yml
- .github/workflows/ide.yml
- .github/workflows/phan.yml
- CHANGELOG.md
- classes/models/NostoOrder.php
- nostotagging.php
> Release 4.4.1 - Prevent division by zero when the total product tax included in the product is zero (Free items without tax)

- CHANGELOG.md
- classes/models/NostoProduct.php
- classes/models/NostoSku.php
- nostotagging.php
- views/templates/hook/header_add-to-cart.tpl
> Release/4.4.2 - Hotfix main product SKU image

- .github/workflows/action.yml
- .github/workflows/ide.yml
- .github/workflows/phan.yml
- CHANGELOG.md
- nostotagging.php
and bump version and update changelog
> Fix compatibility with Prestashop 8.2 
